//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.03 at 02:46:18 PM IST 
//


package generated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}customchecks" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}conformancechecks" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customchecks",
    "conformancechecks"
})
@XmlRootElement(name = "errors")
public class Errors {

    protected List<Customchecks> customchecks;
    protected List<Conformancechecks> conformancechecks;

    /**
     * Gets the value of the customchecks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customchecks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomchecks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Customchecks }
     * 
     * 
     */
    public List<Customchecks> getCustomchecks() {
        if (customchecks == null) {
            customchecks = new ArrayList<Customchecks>();
        }
        return this.customchecks;
    }

    /**
     * Gets the value of the conformancechecks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conformancechecks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConformancechecks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Conformancechecks }
     * 
     * 
     */
    public List<Conformancechecks> getConformancechecks() {
        if (conformancechecks == null) {
            conformancechecks = new ArrayList<Conformancechecks>();
        }
        return this.conformancechecks;
    }

}
