//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.03 at 02:46:18 PM IST 
//


package generated;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}errors"/&gt;
 *         &lt;element ref="{}info"/&gt;
 *         &lt;element ref="{}summary"/&gt;
 *         &lt;element ref="{}Program"/&gt;
 *         &lt;element ref="{}substream"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="CPLName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Info" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Error" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="Warning" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="parent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="RefFilePath" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="StartTimecode" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="FileName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FolderName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="multiview" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="viewcount" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="views" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EncodedDuration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TimecodeType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="attemptId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="AdId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorsOrInfoOrSummary"
})
@XmlRootElement(name = "streamnode")
public class Streamnode {

    @XmlElements({
        @XmlElement(name = "errors", type = Errors.class),
        @XmlElement(name = "info", type = Info.class),
        @XmlElement(name = "summary", type = Summary.class),
        @XmlElement(name = "Program", type = Program.class),
        @XmlElement(name = "substream", type = Substream.class)
    })
    protected List<Object> errorsOrInfoOrSummary;
    @XmlAttribute(name = "CPLName")
    protected String cplName;
    @XmlAttribute(name = "Info")
    protected String info;
    @XmlAttribute(name = "name")
    protected String streamName;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "Error")
    protected BigInteger error;
    @XmlAttribute(name = "Warning")
    protected BigInteger warning;
    @XmlAttribute(name = "parent", required = true)
    protected BigInteger parent;
    @XmlAttribute(name = "RefFilePath")
    protected String refFilePath;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "StartTimecode")
    protected BigInteger startTimecode;
    @XmlAttribute(name = "FileName")
    protected String fileName;
    @XmlAttribute(name = "FolderName")
    protected String folderName;
    @XmlAttribute(name = "multiview")
    protected String multiview;
    @XmlAttribute(name = "viewcount")
    protected String viewcount;
    @XmlAttribute(name = "views")
    protected String views;
    @XmlAttribute(name = "EncodedDuration")
    protected String encodedDuration;
    @XmlAttribute(name = "TimecodeType")
    protected String timecodeType;
    @XmlAttribute(name = "attemptId")
    protected String attemptId;
    @XmlAttribute(name = "AdId")
    protected String adId;

    /**
     * Gets the value of the errorsOrInfoOrSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorsOrInfoOrSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorsOrInfoOrSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Errors }
     * {@link Info }
     * {@link Summary }
     * {@link Program }
     * {@link Substream }
     * 
     * 
     */
    public List<Object> getErrorsOrInfoOrSummary() {
        if (errorsOrInfoOrSummary == null) {
            errorsOrInfoOrSummary = new ArrayList<Object>();
        }
        return this.errorsOrInfoOrSummary;
    }

    /**
     * Gets the value of the cplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPLName() {
        return cplName;
    }

    /**
     * Sets the value of the cplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPLName(String value) {
        this.cplName = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the streamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamName() {
        return streamName;
    }

    /**
     * Sets the value of the streamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamName(String value) {
        this.streamName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setError(BigInteger value) {
        this.error = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWarning(BigInteger value) {
        this.warning = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParent(BigInteger value) {
        this.parent = value;
    }

    /**
     * Gets the value of the refFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefFilePath() {
        return refFilePath;
    }

    /**
     * Sets the value of the refFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefFilePath(String value) {
        this.refFilePath = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the startTimecode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartTimecode() {
        return startTimecode;
    }

    /**
     * Sets the value of the startTimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartTimecode(BigInteger value) {
        this.startTimecode = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the folderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * Sets the value of the folderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderName(String value) {
        this.folderName = value;
    }

    /**
     * Gets the value of the multiview property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiview() {
        return multiview;
    }

    /**
     * Sets the value of the multiview property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiview(String value) {
        this.multiview = value;
    }

    /**
     * Gets the value of the viewcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewcount() {
        return viewcount;
    }

    /**
     * Sets the value of the viewcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewcount(String value) {
        this.viewcount = value;
    }

    /**
     * Gets the value of the views property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViews() {
        return views;
    }

    /**
     * Sets the value of the views property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViews(String value) {
        this.views = value;
    }

    /**
     * Gets the value of the encodedDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodedDuration() {
        return encodedDuration;
    }

    /**
     * Sets the value of the encodedDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodedDuration(String value) {
        this.encodedDuration = value;
    }

    /**
     * Gets the value of the timecodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimecodeType() {
        return timecodeType;
    }

    /**
     * Sets the value of the timecodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimecodeType(String value) {
        this.timecodeType = value;
    }

    /**
     * Gets the value of the attemptId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttemptId() {
        return attemptId;
    }

    /**
     * Sets the value of the attemptId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttemptId(String value) {
        this.attemptId = value;
    }

    /**
     * Gets the value of the adId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdId() {
        return adId;
    }

    /**
     * Sets the value of the adId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdId(String value) {
        this.adId = value;
    }

}
