//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.03 at 02:46:18 PM IST 
//


package generated;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for error complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="error"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}comment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}Params" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ProgramId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FileName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="FolderName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="variant" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="playlistFile" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="itemIndex" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="subitem" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="section" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ignore" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="timecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="synopsis" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="location" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="checkId" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="FrameDuration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SMPTETimecodeDuration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TimeCodeDuration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="count" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="EBUCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ignored"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="rap_sequence_num"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *             &lt;fractionDigits value="0"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="to_merge"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="true"/&gt;
 *             &lt;enumeration value="false"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="severity"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Fatal"/&gt;
 *             &lt;enumeration value="Warning"/&gt;
 *             &lt;enumeration value="Serious"/&gt;
 *             &lt;enumeration value="Info"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="smptetimecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="item" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="starttimecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="startsmptetimecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="startframeindex" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="endtimecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="endsmptetimecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="endframeindex" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="durationsmptetimecode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "error", propOrder = {
    "comment",
    "params"
})
public class Error {

    protected List<Comment> comment;
    @XmlElement(name = "Params")
    protected List<Params> params;
    @XmlAttribute(name = "ProgramId")
    protected String programId;
    @XmlAttribute(name = "FileName")
    protected String fileName;
    @XmlAttribute(name = "FolderName")
    protected String folderName;
    @XmlAttribute(name = "variant")
    protected String variant;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "playlistFile")
    protected String playlistFile;
    @XmlAttribute(name = "index")
    protected String index;
    @XmlAttribute(name = "itemIndex")
    protected String itemIndex;
    @XmlAttribute(name = "subitem")
    protected String subitem;
    @XmlAttribute(name = "section")
    protected String section;
    @XmlAttribute(name = "ignore")
    protected String ignore;
    @XmlAttribute(name = "level")
    protected String level;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "timecode")
    protected String timecode;
    @XmlAttribute(name = "synopsis")
    protected String synopsis;
    @XmlAttribute(name = "location")
    protected String location;
    @XmlAttribute(name = "checkId")
    protected BigInteger checkId;
    @XmlAttribute(name = "FrameDuration")
    protected String frameDuration;
    @XmlAttribute(name = "SMPTETimecodeDuration")
    protected String smpteTimecodeDuration;
    @XmlAttribute(name = "TimeCodeDuration")
    protected String timeCodeDuration;
    @XmlAttribute(name = "count")
    protected String count;
    @XmlAttribute(name = "EBUCode")
    protected String ebuCode;
    @XmlAttribute(name = "ignored")
    protected String ignored;
    @XmlAttribute(name = "rap_sequence_num")
    protected BigInteger rapSequenceNum;
    @XmlAttribute(name = "to_merge")
    protected String toMerge;
    @XmlAttribute(name = "severity")
    protected String severity;
    @XmlAttribute(name = "smptetimecode")
    protected String smptetimecode;
    @XmlAttribute(name = "item")
    protected String item;
    @XmlAttribute(name = "starttimecode")
    protected String starttimecode;
    @XmlAttribute(name = "startsmptetimecode")
    protected String startsmptetimecode;
    @XmlAttribute(name = "startframeindex")
    protected String startframeindex;
    @XmlAttribute(name = "endtimecode")
    protected String endtimecode;
    @XmlAttribute(name = "endsmptetimecode")
    protected String endsmptetimecode;
    @XmlAttribute(name = "endframeindex")
    protected String endframeindex;
    @XmlAttribute(name = "durationsmptetimecode")
    protected String durationsmptetimecode;

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<Comment>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the params property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the params property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Params }
     * 
     * 
     */
    public List<Params> getParams() {
        if (params == null) {
            params = new ArrayList<Params>();
        }
        return this.params;
    }

    /**
     * Gets the value of the programId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramId() {
        return programId;
    }

    /**
     * Sets the value of the programId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramId(String value) {
        this.programId = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the folderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * Sets the value of the folderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderName(String value) {
        this.folderName = value;
    }

    /**
     * Gets the value of the variant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariant() {
        return variant;
    }

    /**
     * Sets the value of the variant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariant(String value) {
        this.variant = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the playlistFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaylistFile() {
        return playlistFile;
    }

    /**
     * Sets the value of the playlistFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaylistFile(String value) {
        this.playlistFile = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the itemIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemIndex() {
        return itemIndex;
    }

    /**
     * Sets the value of the itemIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemIndex(String value) {
        this.itemIndex = value;
    }

    /**
     * Gets the value of the subitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubitem() {
        return subitem;
    }

    /**
     * Sets the value of the subitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubitem(String value) {
        this.subitem = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

    /**
     * Gets the value of the ignore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnore() {
        return ignore;
    }

    /**
     * Sets the value of the ignore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnore(String value) {
        this.ignore = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the timecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimecode() {
        return timecode;
    }

    /**
     * Sets the value of the timecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimecode(String value) {
        this.timecode = value;
    }

    /**
     * Gets the value of the synopsis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynopsis() {
        return synopsis;
    }

    /**
     * Sets the value of the synopsis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynopsis(String value) {
        this.synopsis = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the checkId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCheckId() {
        return checkId;
    }

    /**
     * Sets the value of the checkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCheckId(BigInteger value) {
        this.checkId = value;
    }

    /**
     * Gets the value of the frameDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameDuration() {
        return frameDuration;
    }

    /**
     * Sets the value of the frameDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameDuration(String value) {
        this.frameDuration = value;
    }

    /**
     * Gets the value of the smpteTimecodeDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMPTETimecodeDuration() {
        return smpteTimecodeDuration;
    }

    /**
     * Sets the value of the smpteTimecodeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMPTETimecodeDuration(String value) {
        this.smpteTimecodeDuration = value;
    }

    /**
     * Gets the value of the timeCodeDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeCodeDuration() {
        return timeCodeDuration;
    }

    /**
     * Sets the value of the timeCodeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeCodeDuration(String value) {
        this.timeCodeDuration = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the ebuCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBUCode() {
        return ebuCode;
    }

    /**
     * Sets the value of the ebuCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBUCode(String value) {
        this.ebuCode = value;
    }

    /**
     * Gets the value of the ignored property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnored() {
        return ignored;
    }

    /**
     * Sets the value of the ignored property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnored(String value) {
        this.ignored = value;
    }

    /**
     * Gets the value of the rapSequenceNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRapSequenceNum() {
        return rapSequenceNum;
    }

    /**
     * Sets the value of the rapSequenceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRapSequenceNum(BigInteger value) {
        this.rapSequenceNum = value;
    }

    /**
     * Gets the value of the toMerge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToMerge() {
        return toMerge;
    }

    /**
     * Sets the value of the toMerge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToMerge(String value) {
        this.toMerge = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }

    /**
     * Gets the value of the smptetimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmptetimecode() {
        return smptetimecode;
    }

    /**
     * Sets the value of the smptetimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmptetimecode(String value) {
        this.smptetimecode = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItem(String value) {
        this.item = value;
    }

    /**
     * Gets the value of the starttimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStarttimecode() {
        return starttimecode;
    }

    /**
     * Sets the value of the starttimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStarttimecode(String value) {
        this.starttimecode = value;
    }

    /**
     * Gets the value of the startsmptetimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartsmptetimecode() {
        return startsmptetimecode;
    }

    /**
     * Sets the value of the startsmptetimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartsmptetimecode(String value) {
        this.startsmptetimecode = value;
    }

    /**
     * Gets the value of the startframeindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartframeindex() {
        return startframeindex;
    }

    /**
     * Sets the value of the startframeindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartframeindex(String value) {
        this.startframeindex = value;
    }

    /**
     * Gets the value of the endtimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndtimecode() {
        return endtimecode;
    }

    /**
     * Sets the value of the endtimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndtimecode(String value) {
        this.endtimecode = value;
    }

    /**
     * Gets the value of the endsmptetimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndsmptetimecode() {
        return endsmptetimecode;
    }

    /**
     * Sets the value of the endsmptetimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndsmptetimecode(String value) {
        this.endsmptetimecode = value;
    }

    /**
     * Gets the value of the endframeindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndframeindex() {
        return endframeindex;
    }

    /**
     * Sets the value of the endframeindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndframeindex(String value) {
        this.endframeindex = value;
    }

    /**
     * Gets the value of the durationsmptetimecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationsmptetimecode() {
        return durationsmptetimecode;
    }

    /**
     * Sets the value of the durationsmptetimecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationsmptetimecode(String value) {
        this.durationsmptetimecode = value;
    }

}
